# Generated by Django 5.2 on 2025-04-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedometerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hall_sensor', models.BooleanField()),
                ('rgb_led', models.CharField(max_length=20)),
                ('buzzer', models.BooleanField()),
                ('switch1', models.BooleanField()),
                ('switch2', models.BooleanField()),
            ],
        ),
    ]
