# Generated by Django 5.2 on 2025-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedometerdata',
            name='acceleration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='trip_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
