# Generated by Django 5.2 on 2025-04-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedo', '0002_speedometerdata_acceleration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedometerdata',
            name='device_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
