# Generated by Django 5.2 on 2025-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedo', '0003_alter_speedometerdata_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedometerdata',
            name='acceleration',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='battery_level',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='acceleration_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='acceleration_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='acceleration_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='avg_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='battery',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='speedometerdata',
            name='max_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='speedometerdata',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='speedometerdata',
            name='device_id',
            field=models.CharField(default='ESP32-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='speedometerdata',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='speedometerdata',
            name='trip_time',
            field=models.IntegerField(default=0),
        ),
    ]
