# Generated by Django 5.2 on 2025-05-02 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedo', '0005_route_routepoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepoint',
            name='route',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='acceleration_x',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='acceleration_y',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='acceleration_z',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='avg_speed',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='speedometerdata',
            name='trip_time',
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RoutePoint',
        ),
    ]
