# Generated by Django 5.1.4 on 2025-05-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedo', '0002_add_pairingcode'),
        ('speedo', '0006_remove_routepoint_route_and_more'),
    ]

    operations = [
    ]
